### ISSUE TITLE
Recommended installation?

### ISSUE THREAD

**Issue by michael-petersen** [ilikecubesnstuff/commensurability#1]
The package seems to work with `pip install .`, just checking that is the preferred way to install. Perhaps a Quickstart guide in a README file explaining how to get to the first plot?

**Comment by michael-petersen** [comment]
To install with a specific python version, don't forget to `python3.11 -m pip install .` (for example).

**Comment by michael-petersen** [comment]
Until this is a registered package, don't forget that you might need to force the installation: `python3.11 -m pip install . --force`.

**Comment by ilikecubesnstuff** [comment]
This package is now published to PyPI, so `pip install commensurability` works as the preferred installation method.
