### ISSUE TITLE
Dependency on iext=1.0.0

### ISSUE THREAD

**Issue by michael-petersen** [ilikecubesnstuff/commensurability#9]
The example cases depend on iext 1.0.0, but the current version is 1.1.0. See example:

https://github.com/ilikecubesnstuff/commensurability/blob/ef7666e624e68d90ed2cf71a2f0c90601620451f/examples/using_galpy/environment.yml#L81

**Comment by ilikecubesnstuff** [comment]
I think it's best to remove the conda environment setup files now—the `agama`/`gala`/`galpy` resources better describe the setup for those packages, and they are now linked in the README.
